//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::Side;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
#[derive(Debug)]
pub struct SendTake {
    /// market
    pub market: solana_pubkey::Pubkey,
    /// the request queue
    pub request_queue: solana_pubkey::Pubkey,
    /// the event queue
    pub event_queue: solana_pubkey::Pubkey,
    /// bids
    pub bids: solana_pubkey::Pubkey,
    /// asks
    pub asks: solana_pubkey::Pubkey,
    /// the coin currency wallet account
    pub coin_currency_wallet: solana_pubkey::Pubkey,
    /// the price currency wallet account
    pub price_currency_wallet: solana_pubkey::Pubkey,
    /// signer
    pub signer: solana_pubkey::Pubkey,
    /// coin vault
    pub coin_vault: solana_pubkey::Pubkey,
    /// pc vault
    pub pc_vault: solana_pubkey::Pubkey,
    /// spl token program
    pub spl_token_program: solana_pubkey::Pubkey,
    /// (optional) the (M)SRM account used for fee discounts
    pub fee_discounts: solana_pubkey::Pubkey,
}

impl SendTake {
    pub fn instruction(&self, args: SendTakeInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: SendTakeInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(12 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.market, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.request_queue,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.event_queue,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.bids, false));
        accounts.push(solana_instruction::AccountMeta::new(self.asks, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.coin_currency_wallet,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.price_currency_wallet,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.signer,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.coin_vault, false));
        accounts.push(solana_instruction::AccountMeta::new(self.pc_vault, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.spl_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.fee_discounts,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = borsh::to_vec(&SendTakeInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::OPEN_BOOK_DEX_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SendTakeInstructionData {
    discriminator: [u8; 8],
}

impl SendTakeInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [248, 142, 177, 108, 46, 157, 229, 83],
        }
    }
}

impl Default for SendTakeInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SendTakeInstructionArgs {
    pub side: Side,
    pub limit_price: u64,
    pub max_coin_qty: u64,
    pub max_native_pc_qty_including_fees: u64,
    pub min_coin_qty: u64,
    pub min_native_pc_qty: u64,
    pub limit: u16,
}

/// Instruction builder for `SendTake`.
///
/// ### Accounts:
///
///   0. `[writable]` market
///   1. `[writable]` request_queue
///   2. `[writable]` event_queue
///   3. `[writable]` bids
///   4. `[writable]` asks
///   5. `[writable]` coin_currency_wallet
///   6. `[writable]` price_currency_wallet
///   7. `[]` signer
///   8. `[writable]` coin_vault
///   9. `[writable]` pc_vault
///   10. `[optional]` spl_token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   11. `[]` fee_discounts
#[derive(Clone, Debug, Default)]
pub struct SendTakeBuilder {
    market: Option<solana_pubkey::Pubkey>,
    request_queue: Option<solana_pubkey::Pubkey>,
    event_queue: Option<solana_pubkey::Pubkey>,
    bids: Option<solana_pubkey::Pubkey>,
    asks: Option<solana_pubkey::Pubkey>,
    coin_currency_wallet: Option<solana_pubkey::Pubkey>,
    price_currency_wallet: Option<solana_pubkey::Pubkey>,
    signer: Option<solana_pubkey::Pubkey>,
    coin_vault: Option<solana_pubkey::Pubkey>,
    pc_vault: Option<solana_pubkey::Pubkey>,
    spl_token_program: Option<solana_pubkey::Pubkey>,
    fee_discounts: Option<solana_pubkey::Pubkey>,
    side: Option<Side>,
    limit_price: Option<u64>,
    max_coin_qty: Option<u64>,
    max_native_pc_qty_including_fees: Option<u64>,
    min_coin_qty: Option<u64>,
    min_native_pc_qty: Option<u64>,
    limit: Option<u16>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl SendTakeBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// market
    #[inline(always)]
    pub fn market(&mut self, market: solana_pubkey::Pubkey) -> &mut Self {
        self.market = Some(market);
        self
    }
    /// the request queue
    #[inline(always)]
    pub fn request_queue(&mut self, request_queue: solana_pubkey::Pubkey) -> &mut Self {
        self.request_queue = Some(request_queue);
        self
    }
    /// the event queue
    #[inline(always)]
    pub fn event_queue(&mut self, event_queue: solana_pubkey::Pubkey) -> &mut Self {
        self.event_queue = Some(event_queue);
        self
    }
    /// bids
    #[inline(always)]
    pub fn bids(&mut self, bids: solana_pubkey::Pubkey) -> &mut Self {
        self.bids = Some(bids);
        self
    }
    /// asks
    #[inline(always)]
    pub fn asks(&mut self, asks: solana_pubkey::Pubkey) -> &mut Self {
        self.asks = Some(asks);
        self
    }
    /// the coin currency wallet account
    #[inline(always)]
    pub fn coin_currency_wallet(
        &mut self,
        coin_currency_wallet: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.coin_currency_wallet = Some(coin_currency_wallet);
        self
    }
    /// the price currency wallet account
    #[inline(always)]
    pub fn price_currency_wallet(
        &mut self,
        price_currency_wallet: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.price_currency_wallet = Some(price_currency_wallet);
        self
    }
    /// signer
    #[inline(always)]
    pub fn signer(&mut self, signer: solana_pubkey::Pubkey) -> &mut Self {
        self.signer = Some(signer);
        self
    }
    /// coin vault
    #[inline(always)]
    pub fn coin_vault(&mut self, coin_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.coin_vault = Some(coin_vault);
        self
    }
    /// pc vault
    #[inline(always)]
    pub fn pc_vault(&mut self, pc_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.pc_vault = Some(pc_vault);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    /// spl token program
    #[inline(always)]
    pub fn spl_token_program(&mut self, spl_token_program: solana_pubkey::Pubkey) -> &mut Self {
        self.spl_token_program = Some(spl_token_program);
        self
    }
    /// (optional) the (M)SRM account used for fee discounts
    #[inline(always)]
    pub fn fee_discounts(&mut self, fee_discounts: solana_pubkey::Pubkey) -> &mut Self {
        self.fee_discounts = Some(fee_discounts);
        self
    }
    #[inline(always)]
    pub fn side(&mut self, side: Side) -> &mut Self {
        self.side = Some(side);
        self
    }
    #[inline(always)]
    pub fn limit_price(&mut self, limit_price: u64) -> &mut Self {
        self.limit_price = Some(limit_price);
        self
    }
    #[inline(always)]
    pub fn max_coin_qty(&mut self, max_coin_qty: u64) -> &mut Self {
        self.max_coin_qty = Some(max_coin_qty);
        self
    }
    #[inline(always)]
    pub fn max_native_pc_qty_including_fees(
        &mut self,
        max_native_pc_qty_including_fees: u64,
    ) -> &mut Self {
        self.max_native_pc_qty_including_fees = Some(max_native_pc_qty_including_fees);
        self
    }
    #[inline(always)]
    pub fn min_coin_qty(&mut self, min_coin_qty: u64) -> &mut Self {
        self.min_coin_qty = Some(min_coin_qty);
        self
    }
    #[inline(always)]
    pub fn min_native_pc_qty(&mut self, min_native_pc_qty: u64) -> &mut Self {
        self.min_native_pc_qty = Some(min_native_pc_qty);
        self
    }
    #[inline(always)]
    pub fn limit(&mut self, limit: u16) -> &mut Self {
        self.limit = Some(limit);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = SendTake {
            market: self.market.expect("market is not set"),
            request_queue: self.request_queue.expect("request_queue is not set"),
            event_queue: self.event_queue.expect("event_queue is not set"),
            bids: self.bids.expect("bids is not set"),
            asks: self.asks.expect("asks is not set"),
            coin_currency_wallet: self
                .coin_currency_wallet
                .expect("coin_currency_wallet is not set"),
            price_currency_wallet: self
                .price_currency_wallet
                .expect("price_currency_wallet is not set"),
            signer: self.signer.expect("signer is not set"),
            coin_vault: self.coin_vault.expect("coin_vault is not set"),
            pc_vault: self.pc_vault.expect("pc_vault is not set"),
            spl_token_program: self.spl_token_program.unwrap_or(solana_pubkey::pubkey!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            fee_discounts: self.fee_discounts.expect("fee_discounts is not set"),
        };
        let args = SendTakeInstructionArgs {
            side: self.side.clone().expect("side is not set"),
            limit_price: self.limit_price.clone().expect("limit_price is not set"),
            max_coin_qty: self.max_coin_qty.clone().expect("max_coin_qty is not set"),
            max_native_pc_qty_including_fees: self
                .max_native_pc_qty_including_fees
                .clone()
                .expect("max_native_pc_qty_including_fees is not set"),
            min_coin_qty: self.min_coin_qty.clone().expect("min_coin_qty is not set"),
            min_native_pc_qty: self
                .min_native_pc_qty
                .clone()
                .expect("min_native_pc_qty is not set"),
            limit: self.limit.clone().expect("limit is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `send_take` CPI accounts.
pub struct SendTakeCpiAccounts<'a, 'b> {
    /// market
    pub market: &'b solana_account_info::AccountInfo<'a>,
    /// the request queue
    pub request_queue: &'b solana_account_info::AccountInfo<'a>,
    /// the event queue
    pub event_queue: &'b solana_account_info::AccountInfo<'a>,
    /// bids
    pub bids: &'b solana_account_info::AccountInfo<'a>,
    /// asks
    pub asks: &'b solana_account_info::AccountInfo<'a>,
    /// the coin currency wallet account
    pub coin_currency_wallet: &'b solana_account_info::AccountInfo<'a>,
    /// the price currency wallet account
    pub price_currency_wallet: &'b solana_account_info::AccountInfo<'a>,
    /// signer
    pub signer: &'b solana_account_info::AccountInfo<'a>,
    /// coin vault
    pub coin_vault: &'b solana_account_info::AccountInfo<'a>,
    /// pc vault
    pub pc_vault: &'b solana_account_info::AccountInfo<'a>,
    /// spl token program
    pub spl_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// (optional) the (M)SRM account used for fee discounts
    pub fee_discounts: &'b solana_account_info::AccountInfo<'a>,
}

/// `send_take` CPI instruction.
pub struct SendTakeCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// market
    pub market: &'b solana_account_info::AccountInfo<'a>,
    /// the request queue
    pub request_queue: &'b solana_account_info::AccountInfo<'a>,
    /// the event queue
    pub event_queue: &'b solana_account_info::AccountInfo<'a>,
    /// bids
    pub bids: &'b solana_account_info::AccountInfo<'a>,
    /// asks
    pub asks: &'b solana_account_info::AccountInfo<'a>,
    /// the coin currency wallet account
    pub coin_currency_wallet: &'b solana_account_info::AccountInfo<'a>,
    /// the price currency wallet account
    pub price_currency_wallet: &'b solana_account_info::AccountInfo<'a>,
    /// signer
    pub signer: &'b solana_account_info::AccountInfo<'a>,
    /// coin vault
    pub coin_vault: &'b solana_account_info::AccountInfo<'a>,
    /// pc vault
    pub pc_vault: &'b solana_account_info::AccountInfo<'a>,
    /// spl token program
    pub spl_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// (optional) the (M)SRM account used for fee discounts
    pub fee_discounts: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: SendTakeInstructionArgs,
}

impl<'a, 'b> SendTakeCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: SendTakeCpiAccounts<'a, 'b>,
        args: SendTakeInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            market: accounts.market,
            request_queue: accounts.request_queue,
            event_queue: accounts.event_queue,
            bids: accounts.bids,
            asks: accounts.asks,
            coin_currency_wallet: accounts.coin_currency_wallet,
            price_currency_wallet: accounts.price_currency_wallet,
            signer: accounts.signer,
            coin_vault: accounts.coin_vault,
            pc_vault: accounts.pc_vault,
            spl_token_program: accounts.spl_token_program,
            fee_discounts: accounts.fee_discounts,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(12 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(
            *self.market.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.request_queue.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.event_queue.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.bids.key, false));
        accounts.push(solana_instruction::AccountMeta::new(*self.asks.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.coin_currency_wallet.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.price_currency_wallet.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.signer.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.coin_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.pc_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.spl_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.fee_discounts.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = borsh::to_vec(&SendTakeInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::OPEN_BOOK_DEX_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(13 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.market.clone());
        account_infos.push(self.request_queue.clone());
        account_infos.push(self.event_queue.clone());
        account_infos.push(self.bids.clone());
        account_infos.push(self.asks.clone());
        account_infos.push(self.coin_currency_wallet.clone());
        account_infos.push(self.price_currency_wallet.clone());
        account_infos.push(self.signer.clone());
        account_infos.push(self.coin_vault.clone());
        account_infos.push(self.pc_vault.clone());
        account_infos.push(self.spl_token_program.clone());
        account_infos.push(self.fee_discounts.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `SendTake` via CPI.
///
/// ### Accounts:
///
///   0. `[writable]` market
///   1. `[writable]` request_queue
///   2. `[writable]` event_queue
///   3. `[writable]` bids
///   4. `[writable]` asks
///   5. `[writable]` coin_currency_wallet
///   6. `[writable]` price_currency_wallet
///   7. `[]` signer
///   8. `[writable]` coin_vault
///   9. `[writable]` pc_vault
///   10. `[]` spl_token_program
///   11. `[]` fee_discounts
#[derive(Clone, Debug)]
pub struct SendTakeCpiBuilder<'a, 'b> {
    instruction: Box<SendTakeCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> SendTakeCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(SendTakeCpiBuilderInstruction {
            __program: program,
            market: None,
            request_queue: None,
            event_queue: None,
            bids: None,
            asks: None,
            coin_currency_wallet: None,
            price_currency_wallet: None,
            signer: None,
            coin_vault: None,
            pc_vault: None,
            spl_token_program: None,
            fee_discounts: None,
            side: None,
            limit_price: None,
            max_coin_qty: None,
            max_native_pc_qty_including_fees: None,
            min_coin_qty: None,
            min_native_pc_qty: None,
            limit: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// market
    #[inline(always)]
    pub fn market(&mut self, market: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.market = Some(market);
        self
    }
    /// the request queue
    #[inline(always)]
    pub fn request_queue(
        &mut self,
        request_queue: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.request_queue = Some(request_queue);
        self
    }
    /// the event queue
    #[inline(always)]
    pub fn event_queue(
        &mut self,
        event_queue: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.event_queue = Some(event_queue);
        self
    }
    /// bids
    #[inline(always)]
    pub fn bids(&mut self, bids: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.bids = Some(bids);
        self
    }
    /// asks
    #[inline(always)]
    pub fn asks(&mut self, asks: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.asks = Some(asks);
        self
    }
    /// the coin currency wallet account
    #[inline(always)]
    pub fn coin_currency_wallet(
        &mut self,
        coin_currency_wallet: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.coin_currency_wallet = Some(coin_currency_wallet);
        self
    }
    /// the price currency wallet account
    #[inline(always)]
    pub fn price_currency_wallet(
        &mut self,
        price_currency_wallet: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.price_currency_wallet = Some(price_currency_wallet);
        self
    }
    /// signer
    #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.signer = Some(signer);
        self
    }
    /// coin vault
    #[inline(always)]
    pub fn coin_vault(
        &mut self,
        coin_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.coin_vault = Some(coin_vault);
        self
    }
    /// pc vault
    #[inline(always)]
    pub fn pc_vault(&mut self, pc_vault: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.pc_vault = Some(pc_vault);
        self
    }
    /// spl token program
    #[inline(always)]
    pub fn spl_token_program(
        &mut self,
        spl_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.spl_token_program = Some(spl_token_program);
        self
    }
    /// (optional) the (M)SRM account used for fee discounts
    #[inline(always)]
    pub fn fee_discounts(
        &mut self,
        fee_discounts: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.fee_discounts = Some(fee_discounts);
        self
    }
    #[inline(always)]
    pub fn side(&mut self, side: Side) -> &mut Self {
        self.instruction.side = Some(side);
        self
    }
    #[inline(always)]
    pub fn limit_price(&mut self, limit_price: u64) -> &mut Self {
        self.instruction.limit_price = Some(limit_price);
        self
    }
    #[inline(always)]
    pub fn max_coin_qty(&mut self, max_coin_qty: u64) -> &mut Self {
        self.instruction.max_coin_qty = Some(max_coin_qty);
        self
    }
    #[inline(always)]
    pub fn max_native_pc_qty_including_fees(
        &mut self,
        max_native_pc_qty_including_fees: u64,
    ) -> &mut Self {
        self.instruction.max_native_pc_qty_including_fees = Some(max_native_pc_qty_including_fees);
        self
    }
    #[inline(always)]
    pub fn min_coin_qty(&mut self, min_coin_qty: u64) -> &mut Self {
        self.instruction.min_coin_qty = Some(min_coin_qty);
        self
    }
    #[inline(always)]
    pub fn min_native_pc_qty(&mut self, min_native_pc_qty: u64) -> &mut Self {
        self.instruction.min_native_pc_qty = Some(min_native_pc_qty);
        self
    }
    #[inline(always)]
    pub fn limit(&mut self, limit: u16) -> &mut Self {
        self.instruction.limit = Some(limit);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        let args = SendTakeInstructionArgs {
            side: self.instruction.side.clone().expect("side is not set"),
            limit_price: self
                .instruction
                .limit_price
                .clone()
                .expect("limit_price is not set"),
            max_coin_qty: self
                .instruction
                .max_coin_qty
                .clone()
                .expect("max_coin_qty is not set"),
            max_native_pc_qty_including_fees: self
                .instruction
                .max_native_pc_qty_including_fees
                .clone()
                .expect("max_native_pc_qty_including_fees is not set"),
            min_coin_qty: self
                .instruction
                .min_coin_qty
                .clone()
                .expect("min_coin_qty is not set"),
            min_native_pc_qty: self
                .instruction
                .min_native_pc_qty
                .clone()
                .expect("min_native_pc_qty is not set"),
            limit: self.instruction.limit.clone().expect("limit is not set"),
        };
        let instruction = SendTakeCpi {
            __program: self.instruction.__program,

            market: self.instruction.market.expect("market is not set"),

            request_queue: self
                .instruction
                .request_queue
                .expect("request_queue is not set"),

            event_queue: self
                .instruction
                .event_queue
                .expect("event_queue is not set"),

            bids: self.instruction.bids.expect("bids is not set"),

            asks: self.instruction.asks.expect("asks is not set"),

            coin_currency_wallet: self
                .instruction
                .coin_currency_wallet
                .expect("coin_currency_wallet is not set"),

            price_currency_wallet: self
                .instruction
                .price_currency_wallet
                .expect("price_currency_wallet is not set"),

            signer: self.instruction.signer.expect("signer is not set"),

            coin_vault: self.instruction.coin_vault.expect("coin_vault is not set"),

            pc_vault: self.instruction.pc_vault.expect("pc_vault is not set"),

            spl_token_program: self
                .instruction
                .spl_token_program
                .expect("spl_token_program is not set"),

            fee_discounts: self
                .instruction
                .fee_discounts
                .expect("fee_discounts is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct SendTakeCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    market: Option<&'b solana_account_info::AccountInfo<'a>>,
    request_queue: Option<&'b solana_account_info::AccountInfo<'a>>,
    event_queue: Option<&'b solana_account_info::AccountInfo<'a>>,
    bids: Option<&'b solana_account_info::AccountInfo<'a>>,
    asks: Option<&'b solana_account_info::AccountInfo<'a>>,
    coin_currency_wallet: Option<&'b solana_account_info::AccountInfo<'a>>,
    price_currency_wallet: Option<&'b solana_account_info::AccountInfo<'a>>,
    signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    coin_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    pc_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    spl_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    fee_discounts: Option<&'b solana_account_info::AccountInfo<'a>>,
    side: Option<Side>,
    limit_price: Option<u64>,
    max_coin_qty: Option<u64>,
    max_native_pc_qty_including_fees: Option<u64>,
    min_coin_qty: Option<u64>,
    min_native_pc_qty: Option<u64>,
    limit: Option<u16>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
