//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub mod r#guardian_quote_verify;
pub mod r#guardian_register;
pub mod r#guardian_unregister;
pub mod r#oracle_heartbeat;
pub mod r#oracle_heartbeat_v2;
pub mod r#oracle_init;
pub mod r#oracle_init_svm;
pub mod r#oracle_reset_lut;
pub mod r#oracle_set_configs;
pub mod r#oracle_set_operator;
pub mod r#oracle_sync_lut;
pub mod r#permission_set;
pub mod r#pull_feed_close;
pub mod r#pull_feed_init;
pub mod r#pull_feed_set_configs;
pub mod r#pull_feed_submit_response;
pub mod r#pull_feed_submit_response_consensus;
pub mod r#pull_feed_submit_response_consensus_light;
pub mod r#pull_feed_submit_response_many;
pub mod r#pull_feed_submit_response_svm;
pub mod r#queue_add_mr_enclave;
pub mod r#queue_allow_subsidies;
pub mod r#queue_garbage_collect;
pub mod r#queue_init;
pub mod r#queue_init_svm;
pub mod r#queue_override_svm;
pub mod r#queue_pay_subsidy;
pub mod r#queue_remove_mr_enclave;
pub mod r#queue_reset_vault;
pub mod r#queue_set_configs;
pub mod r#queue_set_ncn;
pub mod r#queue_set_vault;
pub mod r#randomness_commit;
pub mod r#randomness_init;
pub mod r#randomness_reveal;
pub mod r#state_init;
pub mod r#state_set_configs;
pub mod r#test_update_oracle_stats;

pub use self::r#guardian_quote_verify::*;
pub use self::r#guardian_register::*;
pub use self::r#guardian_unregister::*;
pub use self::r#oracle_heartbeat::*;
pub use self::r#oracle_heartbeat_v2::*;
pub use self::r#oracle_init::*;
pub use self::r#oracle_init_svm::*;
pub use self::r#oracle_reset_lut::*;
pub use self::r#oracle_set_configs::*;
pub use self::r#oracle_set_operator::*;
pub use self::r#oracle_sync_lut::*;
pub use self::r#permission_set::*;
pub use self::r#pull_feed_close::*;
pub use self::r#pull_feed_init::*;
pub use self::r#pull_feed_set_configs::*;
pub use self::r#pull_feed_submit_response::*;
pub use self::r#pull_feed_submit_response_consensus::*;
pub use self::r#pull_feed_submit_response_consensus_light::*;
pub use self::r#pull_feed_submit_response_many::*;
pub use self::r#pull_feed_submit_response_svm::*;
pub use self::r#queue_add_mr_enclave::*;
pub use self::r#queue_allow_subsidies::*;
pub use self::r#queue_garbage_collect::*;
pub use self::r#queue_init::*;
pub use self::r#queue_init_svm::*;
pub use self::r#queue_override_svm::*;
pub use self::r#queue_pay_subsidy::*;
pub use self::r#queue_remove_mr_enclave::*;
pub use self::r#queue_reset_vault::*;
pub use self::r#queue_set_configs::*;
pub use self::r#queue_set_ncn::*;
pub use self::r#queue_set_vault::*;
pub use self::r#randomness_commit::*;
pub use self::r#randomness_init::*;
pub use self::r#randomness_reveal::*;
pub use self::r#state_init::*;
pub use self::r#state_set_configs::*;
pub use self::r#test_update_oracle_stats::*;
