//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
#[derive(Debug)]
pub struct QueueOverrideSvm {
    pub oracle: solana_pubkey::Pubkey,

    pub queue: solana_pubkey::Pubkey,

    pub authority: solana_pubkey::Pubkey,

    pub state: solana_pubkey::Pubkey,
}

impl QueueOverrideSvm {
    pub fn instruction(
        &self,
        args: QueueOverrideSvmInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: QueueOverrideSvmInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(4 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.oracle, false));
        accounts.push(solana_instruction::AccountMeta::new(self.queue, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.state, false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = borsh::to_vec(&QueueOverrideSvmInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::SB_ON_DEMAND_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct QueueOverrideSvmInstructionData {
    discriminator: [u8; 8],
}

impl QueueOverrideSvmInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [43, 103, 15, 35, 89, 14, 244, 165],
        }
    }
}

impl Default for QueueOverrideSvmInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct QueueOverrideSvmInstructionArgs {
    pub secp256k1_signer: [u8; 64],
    pub max_quote_verification_age: i64,
    pub mr_enclave: [u8; 32],
    pub slot: u64,
}

/// Instruction builder for `QueueOverrideSvm`.
///
/// ### Accounts:
///
///   0. `[writable]` oracle
///   1. `[writable]` queue
///   2. `[signer]` authority
///   3. `[]` state
#[derive(Clone, Debug, Default)]
pub struct QueueOverrideSvmBuilder {
    oracle: Option<solana_pubkey::Pubkey>,
    queue: Option<solana_pubkey::Pubkey>,
    authority: Option<solana_pubkey::Pubkey>,
    state: Option<solana_pubkey::Pubkey>,
    secp256k1_signer: Option<[u8; 64]>,
    max_quote_verification_age: Option<i64>,
    mr_enclave: Option<[u8; 32]>,
    slot: Option<u64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl QueueOverrideSvmBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn oracle(&mut self, oracle: solana_pubkey::Pubkey) -> &mut Self {
        self.oracle = Some(oracle);
        self
    }
    #[inline(always)]
    pub fn queue(&mut self, queue: solana_pubkey::Pubkey) -> &mut Self {
        self.queue = Some(queue);
        self
    }
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    #[inline(always)]
    pub fn state(&mut self, state: solana_pubkey::Pubkey) -> &mut Self {
        self.state = Some(state);
        self
    }
    #[inline(always)]
    pub fn secp256k1_signer(&mut self, secp256k1_signer: [u8; 64]) -> &mut Self {
        self.secp256k1_signer = Some(secp256k1_signer);
        self
    }
    #[inline(always)]
    pub fn max_quote_verification_age(&mut self, max_quote_verification_age: i64) -> &mut Self {
        self.max_quote_verification_age = Some(max_quote_verification_age);
        self
    }
    #[inline(always)]
    pub fn mr_enclave(&mut self, mr_enclave: [u8; 32]) -> &mut Self {
        self.mr_enclave = Some(mr_enclave);
        self
    }
    #[inline(always)]
    pub fn slot(&mut self, slot: u64) -> &mut Self {
        self.slot = Some(slot);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = QueueOverrideSvm {
            oracle: self.oracle.expect("oracle is not set"),
            queue: self.queue.expect("queue is not set"),
            authority: self.authority.expect("authority is not set"),
            state: self.state.expect("state is not set"),
        };
        let args = QueueOverrideSvmInstructionArgs {
            secp256k1_signer: self
                .secp256k1_signer
                .clone()
                .expect("secp256k1_signer is not set"),
            max_quote_verification_age: self
                .max_quote_verification_age
                .clone()
                .expect("max_quote_verification_age is not set"),
            mr_enclave: self.mr_enclave.clone().expect("mr_enclave is not set"),
            slot: self.slot.clone().expect("slot is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `queue_override_svm` CPI accounts.
pub struct QueueOverrideSvmCpiAccounts<'a, 'b> {
    pub oracle: &'b solana_account_info::AccountInfo<'a>,

    pub queue: &'b solana_account_info::AccountInfo<'a>,

    pub authority: &'b solana_account_info::AccountInfo<'a>,

    pub state: &'b solana_account_info::AccountInfo<'a>,
}

/// `queue_override_svm` CPI instruction.
pub struct QueueOverrideSvmCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub oracle: &'b solana_account_info::AccountInfo<'a>,

    pub queue: &'b solana_account_info::AccountInfo<'a>,

    pub authority: &'b solana_account_info::AccountInfo<'a>,

    pub state: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: QueueOverrideSvmInstructionArgs,
}

impl<'a, 'b> QueueOverrideSvmCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: QueueOverrideSvmCpiAccounts<'a, 'b>,
        args: QueueOverrideSvmInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            oracle: accounts.oracle,
            queue: accounts.queue,
            authority: accounts.authority,
            state: accounts.state,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(4 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(
            *self.oracle.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.queue.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.state.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = borsh::to_vec(&QueueOverrideSvmInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::SB_ON_DEMAND_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(5 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.oracle.clone());
        account_infos.push(self.queue.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.state.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `QueueOverrideSvm` via CPI.
///
/// ### Accounts:
///
///   0. `[writable]` oracle
///   1. `[writable]` queue
///   2. `[signer]` authority
///   3. `[]` state
#[derive(Clone, Debug)]
pub struct QueueOverrideSvmCpiBuilder<'a, 'b> {
    instruction: Box<QueueOverrideSvmCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> QueueOverrideSvmCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(QueueOverrideSvmCpiBuilderInstruction {
            __program: program,
            oracle: None,
            queue: None,
            authority: None,
            state: None,
            secp256k1_signer: None,
            max_quote_verification_age: None,
            mr_enclave: None,
            slot: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn oracle(&mut self, oracle: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.oracle = Some(oracle);
        self
    }
    #[inline(always)]
    pub fn queue(&mut self, queue: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.queue = Some(queue);
        self
    }
    #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    #[inline(always)]
    pub fn state(&mut self, state: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.state = Some(state);
        self
    }
    #[inline(always)]
    pub fn secp256k1_signer(&mut self, secp256k1_signer: [u8; 64]) -> &mut Self {
        self.instruction.secp256k1_signer = Some(secp256k1_signer);
        self
    }
    #[inline(always)]
    pub fn max_quote_verification_age(&mut self, max_quote_verification_age: i64) -> &mut Self {
        self.instruction.max_quote_verification_age = Some(max_quote_verification_age);
        self
    }
    #[inline(always)]
    pub fn mr_enclave(&mut self, mr_enclave: [u8; 32]) -> &mut Self {
        self.instruction.mr_enclave = Some(mr_enclave);
        self
    }
    #[inline(always)]
    pub fn slot(&mut self, slot: u64) -> &mut Self {
        self.instruction.slot = Some(slot);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        let args = QueueOverrideSvmInstructionArgs {
            secp256k1_signer: self
                .instruction
                .secp256k1_signer
                .clone()
                .expect("secp256k1_signer is not set"),
            max_quote_verification_age: self
                .instruction
                .max_quote_verification_age
                .clone()
                .expect("max_quote_verification_age is not set"),
            mr_enclave: self
                .instruction
                .mr_enclave
                .clone()
                .expect("mr_enclave is not set"),
            slot: self.instruction.slot.clone().expect("slot is not set"),
        };
        let instruction = QueueOverrideSvmCpi {
            __program: self.instruction.__program,

            oracle: self.instruction.oracle.expect("oracle is not set"),

            queue: self.instruction.queue.expect("queue is not set"),

            authority: self.instruction.authority.expect("authority is not set"),

            state: self.instruction.state.expect("state is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct QueueOverrideSvmCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    oracle: Option<&'b solana_account_info::AccountInfo<'a>>,
    queue: Option<&'b solana_account_info::AccountInfo<'a>>,
    authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    state: Option<&'b solana_account_info::AccountInfo<'a>>,
    secp256k1_signer: Option<[u8; 64]>,
    max_quote_verification_age: Option<i64>,
    mr_enclave: Option<[u8; 32]>,
    slot: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
