//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
#[derive(Debug)]
pub struct RandomnessReveal {
    pub randomness: solana_pubkey::Pubkey,

    pub oracle: solana_pubkey::Pubkey,

    pub queue: solana_pubkey::Pubkey,

    pub stats: solana_pubkey::Pubkey,

    pub authority: solana_pubkey::Pubkey,

    pub payer: solana_pubkey::Pubkey,

    pub recent_slothashes: solana_pubkey::Pubkey,

    pub system_program: solana_pubkey::Pubkey,

    pub reward_escrow: solana_pubkey::Pubkey,

    pub token_program: solana_pubkey::Pubkey,

    pub wrapped_sol_mint: solana_pubkey::Pubkey,

    pub program_state: solana_pubkey::Pubkey,
}

impl RandomnessReveal {
    pub fn instruction(
        &self,
        args: RandomnessRevealInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: RandomnessRevealInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(12 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.randomness, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.oracle,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.queue, false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.stats, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.payer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.recent_slothashes,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.reward_escrow,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.wrapped_sol_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program_state,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = borsh::to_vec(&RandomnessRevealInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::SB_ON_DEMAND_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RandomnessRevealInstructionData {
    discriminator: [u8; 8],
}

impl RandomnessRevealInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [197, 181, 187, 10, 30, 58, 20, 73],
        }
    }
}

impl Default for RandomnessRevealInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RandomnessRevealInstructionArgs {
    pub signature: [u8; 64],
    pub recovery_id: u8,
    pub value: [u8; 32],
}

/// Instruction builder for `RandomnessReveal`.
///
/// ### Accounts:
///
///   0. `[writable]` randomness
///   1. `[]` oracle
///   2. `[]` queue
///   3. `[writable]` stats
///   4. `[signer]` authority
///   5. `[writable, signer]` payer
///   6. `[optional]` recent_slothashes (default to `SysvarS1otHashes111111111111111111111111111`)
///   7. `[optional]` system_program (default to `11111111111111111111111111111111`)
///   8. `[writable]` reward_escrow
///   9. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   10. `[optional]` wrapped_sol_mint (default to `So11111111111111111111111111111111111111112`)
///   11. `[]` program_state
#[derive(Clone, Debug, Default)]
pub struct RandomnessRevealBuilder {
    randomness: Option<solana_pubkey::Pubkey>,
    oracle: Option<solana_pubkey::Pubkey>,
    queue: Option<solana_pubkey::Pubkey>,
    stats: Option<solana_pubkey::Pubkey>,
    authority: Option<solana_pubkey::Pubkey>,
    payer: Option<solana_pubkey::Pubkey>,
    recent_slothashes: Option<solana_pubkey::Pubkey>,
    system_program: Option<solana_pubkey::Pubkey>,
    reward_escrow: Option<solana_pubkey::Pubkey>,
    token_program: Option<solana_pubkey::Pubkey>,
    wrapped_sol_mint: Option<solana_pubkey::Pubkey>,
    program_state: Option<solana_pubkey::Pubkey>,
    signature: Option<[u8; 64]>,
    recovery_id: Option<u8>,
    value: Option<[u8; 32]>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl RandomnessRevealBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn randomness(&mut self, randomness: solana_pubkey::Pubkey) -> &mut Self {
        self.randomness = Some(randomness);
        self
    }
    #[inline(always)]
    pub fn oracle(&mut self, oracle: solana_pubkey::Pubkey) -> &mut Self {
        self.oracle = Some(oracle);
        self
    }
    #[inline(always)]
    pub fn queue(&mut self, queue: solana_pubkey::Pubkey) -> &mut Self {
        self.queue = Some(queue);
        self
    }
    #[inline(always)]
    pub fn stats(&mut self, stats: solana_pubkey::Pubkey) -> &mut Self {
        self.stats = Some(stats);
        self
    }
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    #[inline(always)]
    pub fn payer(&mut self, payer: solana_pubkey::Pubkey) -> &mut Self {
        self.payer = Some(payer);
        self
    }
    /// `[optional account, default to 'SysvarS1otHashes111111111111111111111111111']`
    #[inline(always)]
    pub fn recent_slothashes(&mut self, recent_slothashes: solana_pubkey::Pubkey) -> &mut Self {
        self.recent_slothashes = Some(recent_slothashes);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn reward_escrow(&mut self, reward_escrow: solana_pubkey::Pubkey) -> &mut Self {
        self.reward_escrow = Some(reward_escrow);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    /// `[optional account, default to 'So11111111111111111111111111111111111111112']`
    #[inline(always)]
    pub fn wrapped_sol_mint(&mut self, wrapped_sol_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.wrapped_sol_mint = Some(wrapped_sol_mint);
        self
    }
    #[inline(always)]
    pub fn program_state(&mut self, program_state: solana_pubkey::Pubkey) -> &mut Self {
        self.program_state = Some(program_state);
        self
    }
    #[inline(always)]
    pub fn signature(&mut self, signature: [u8; 64]) -> &mut Self {
        self.signature = Some(signature);
        self
    }
    #[inline(always)]
    pub fn recovery_id(&mut self, recovery_id: u8) -> &mut Self {
        self.recovery_id = Some(recovery_id);
        self
    }
    #[inline(always)]
    pub fn value(&mut self, value: [u8; 32]) -> &mut Self {
        self.value = Some(value);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = RandomnessReveal {
            randomness: self.randomness.expect("randomness is not set"),
            oracle: self.oracle.expect("oracle is not set"),
            queue: self.queue.expect("queue is not set"),
            stats: self.stats.expect("stats is not set"),
            authority: self.authority.expect("authority is not set"),
            payer: self.payer.expect("payer is not set"),
            recent_slothashes: self.recent_slothashes.unwrap_or(solana_pubkey::pubkey!(
                "SysvarS1otHashes111111111111111111111111111"
            )),
            system_program: self
                .system_program
                .unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
            reward_escrow: self.reward_escrow.expect("reward_escrow is not set"),
            token_program: self.token_program.unwrap_or(solana_pubkey::pubkey!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            wrapped_sol_mint: self.wrapped_sol_mint.unwrap_or(solana_pubkey::pubkey!(
                "So11111111111111111111111111111111111111112"
            )),
            program_state: self.program_state.expect("program_state is not set"),
        };
        let args = RandomnessRevealInstructionArgs {
            signature: self.signature.clone().expect("signature is not set"),
            recovery_id: self.recovery_id.clone().expect("recovery_id is not set"),
            value: self.value.clone().expect("value is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `randomness_reveal` CPI accounts.
pub struct RandomnessRevealCpiAccounts<'a, 'b> {
    pub randomness: &'b solana_account_info::AccountInfo<'a>,

    pub oracle: &'b solana_account_info::AccountInfo<'a>,

    pub queue: &'b solana_account_info::AccountInfo<'a>,

    pub stats: &'b solana_account_info::AccountInfo<'a>,

    pub authority: &'b solana_account_info::AccountInfo<'a>,

    pub payer: &'b solana_account_info::AccountInfo<'a>,

    pub recent_slothashes: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub reward_escrow: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub wrapped_sol_mint: &'b solana_account_info::AccountInfo<'a>,

    pub program_state: &'b solana_account_info::AccountInfo<'a>,
}

/// `randomness_reveal` CPI instruction.
pub struct RandomnessRevealCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub randomness: &'b solana_account_info::AccountInfo<'a>,

    pub oracle: &'b solana_account_info::AccountInfo<'a>,

    pub queue: &'b solana_account_info::AccountInfo<'a>,

    pub stats: &'b solana_account_info::AccountInfo<'a>,

    pub authority: &'b solana_account_info::AccountInfo<'a>,

    pub payer: &'b solana_account_info::AccountInfo<'a>,

    pub recent_slothashes: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub reward_escrow: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub wrapped_sol_mint: &'b solana_account_info::AccountInfo<'a>,

    pub program_state: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: RandomnessRevealInstructionArgs,
}

impl<'a, 'b> RandomnessRevealCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: RandomnessRevealCpiAccounts<'a, 'b>,
        args: RandomnessRevealInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            randomness: accounts.randomness,
            oracle: accounts.oracle,
            queue: accounts.queue,
            stats: accounts.stats,
            authority: accounts.authority,
            payer: accounts.payer,
            recent_slothashes: accounts.recent_slothashes,
            system_program: accounts.system_program,
            reward_escrow: accounts.reward_escrow,
            token_program: accounts.token_program,
            wrapped_sol_mint: accounts.wrapped_sol_mint,
            program_state: accounts.program_state,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(12 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(
            *self.randomness.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.oracle.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.queue.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.stats.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.payer.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.recent_slothashes.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.reward_escrow.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.wrapped_sol_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program_state.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = borsh::to_vec(&RandomnessRevealInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::SB_ON_DEMAND_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(13 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.randomness.clone());
        account_infos.push(self.oracle.clone());
        account_infos.push(self.queue.clone());
        account_infos.push(self.stats.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.recent_slothashes.clone());
        account_infos.push(self.system_program.clone());
        account_infos.push(self.reward_escrow.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.wrapped_sol_mint.clone());
        account_infos.push(self.program_state.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `RandomnessReveal` via CPI.
///
/// ### Accounts:
///
///   0. `[writable]` randomness
///   1. `[]` oracle
///   2. `[]` queue
///   3. `[writable]` stats
///   4. `[signer]` authority
///   5. `[writable, signer]` payer
///   6. `[]` recent_slothashes
///   7. `[]` system_program
///   8. `[writable]` reward_escrow
///   9. `[]` token_program
///   10. `[]` wrapped_sol_mint
///   11. `[]` program_state
#[derive(Clone, Debug)]
pub struct RandomnessRevealCpiBuilder<'a, 'b> {
    instruction: Box<RandomnessRevealCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> RandomnessRevealCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(RandomnessRevealCpiBuilderInstruction {
            __program: program,
            randomness: None,
            oracle: None,
            queue: None,
            stats: None,
            authority: None,
            payer: None,
            recent_slothashes: None,
            system_program: None,
            reward_escrow: None,
            token_program: None,
            wrapped_sol_mint: None,
            program_state: None,
            signature: None,
            recovery_id: None,
            value: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn randomness(
        &mut self,
        randomness: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.randomness = Some(randomness);
        self
    }
    #[inline(always)]
    pub fn oracle(&mut self, oracle: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.oracle = Some(oracle);
        self
    }
    #[inline(always)]
    pub fn queue(&mut self, queue: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.queue = Some(queue);
        self
    }
    #[inline(always)]
    pub fn stats(&mut self, stats: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.stats = Some(stats);
        self
    }
    #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }
    #[inline(always)]
    pub fn recent_slothashes(
        &mut self,
        recent_slothashes: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.recent_slothashes = Some(recent_slothashes);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn reward_escrow(
        &mut self,
        reward_escrow: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.reward_escrow = Some(reward_escrow);
        self
    }
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn wrapped_sol_mint(
        &mut self,
        wrapped_sol_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.wrapped_sol_mint = Some(wrapped_sol_mint);
        self
    }
    #[inline(always)]
    pub fn program_state(
        &mut self,
        program_state: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.program_state = Some(program_state);
        self
    }
    #[inline(always)]
    pub fn signature(&mut self, signature: [u8; 64]) -> &mut Self {
        self.instruction.signature = Some(signature);
        self
    }
    #[inline(always)]
    pub fn recovery_id(&mut self, recovery_id: u8) -> &mut Self {
        self.instruction.recovery_id = Some(recovery_id);
        self
    }
    #[inline(always)]
    pub fn value(&mut self, value: [u8; 32]) -> &mut Self {
        self.instruction.value = Some(value);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        let args = RandomnessRevealInstructionArgs {
            signature: self
                .instruction
                .signature
                .clone()
                .expect("signature is not set"),
            recovery_id: self
                .instruction
                .recovery_id
                .clone()
                .expect("recovery_id is not set"),
            value: self.instruction.value.clone().expect("value is not set"),
        };
        let instruction = RandomnessRevealCpi {
            __program: self.instruction.__program,

            randomness: self.instruction.randomness.expect("randomness is not set"),

            oracle: self.instruction.oracle.expect("oracle is not set"),

            queue: self.instruction.queue.expect("queue is not set"),

            stats: self.instruction.stats.expect("stats is not set"),

            authority: self.instruction.authority.expect("authority is not set"),

            payer: self.instruction.payer.expect("payer is not set"),

            recent_slothashes: self
                .instruction
                .recent_slothashes
                .expect("recent_slothashes is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),

            reward_escrow: self
                .instruction
                .reward_escrow
                .expect("reward_escrow is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            wrapped_sol_mint: self
                .instruction
                .wrapped_sol_mint
                .expect("wrapped_sol_mint is not set"),

            program_state: self
                .instruction
                .program_state
                .expect("program_state is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct RandomnessRevealCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    randomness: Option<&'b solana_account_info::AccountInfo<'a>>,
    oracle: Option<&'b solana_account_info::AccountInfo<'a>>,
    queue: Option<&'b solana_account_info::AccountInfo<'a>>,
    stats: Option<&'b solana_account_info::AccountInfo<'a>>,
    authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    recent_slothashes: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    reward_escrow: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    wrapped_sol_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    program_state: Option<&'b solana_account_info::AccountInfo<'a>>,
    signature: Option<[u8; 64]>,
    recovery_id: Option<u8>,
    value: Option<[u8; 32]>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
